name: n8_default_project
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.6
  flutter_screenutil: ^5.8.4
  shared_preferences: ^2.1.2
  zoom_tap_animation: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0




flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/translations/


  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Montserrat-Black.ttf
        - asset: assets/fonts/Inter/Montserrat-BlackItalic.ttf
        - asset: assets/fonts/Inter/Montserrat-Bold.ttf
        - asset: assets/fonts/Inter/Montserrat-BoldItalic.ttf
        - asset: assets/fonts/Inter/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/Inter/Montserrat-ExtraBoldItalic.ttf
        - asset: assets/fonts/Inter/Montserrat-ExtraLight.ttf
        - asset: assets/fonts/Inter/Montserrat-ExtraLightItalic.ttf
        - asset: assets/fonts/Inter/Montserrat-Italic.ttf
        - asset: assets/fonts/Inter/Montserrat-Light.ttf
        - asset: assets/fonts/Inter/Montserrat-LightItalic.ttf
        - asset: assets/fonts/Inter/Montserrat-MediumItalic.ttf
        - asset: assets/fonts/Inter/Montserrat-Medium.ttf
        - asset: assets/fonts/Inter/Montserrat-Regular.ttf
        - asset: assets/fonts/Inter/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Inter/Montserrat-Thin.ttf
        - asset: assets/fonts/Inter/Montserrat-ThinItalic.ttf
